- name: setup redis configuartion
  hosts: redis
  become: yes
  tasks:
    - name: Installing required packages
      package:
        name:
          - gpg
          - unzip
        state: present
        update_cache: yes

    - name: printing gather facts
      debug:
        var: ansible_distribution_release

    - name: Downloading gpg key for redis repo
      get_url:
        url: https://packages.redis.io/gpg
        dest: /tmp/redis.gpg
    
    - name: convert gpg key to keyring format
      command:
        cmd: gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg /tmp/redis.gpg
        creates: /usr/share/keyrings/redis-archive-keyring.gpg

    - name: copy redis repo from local to destination
      template:
        src: ./redis.list.j2
        dest: /etc/apt/sources.list.d/redis.list

    - name: Install cache
      package:
        update_cache: yes

    - name: Install redis
      package:
        name: redis
        state: present

    - name: enable and start the service
      service:
        name: redis-server
        state: started
        enabled: yes
      
    - name: Allowing remote connections
      replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: change protected mode
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: 'protected-mode'
        line: 'protected-mode no'
      notify:
        - restart redis

  handlers:
    - name: restart redis
      systemd:
        name: redis-server
        daemon_reload: yes
        state: restarted